### ISSUE TITLE
Links to RPi images

### ISSUE THREAD

**Issue by Utopiah** [cardonabits/haxo-hw#62]
cf printed quick start guide : 

1. https://bit.ly/haxo-rpiz
2. https://bit.ly/haxo-rpi4
3. https://bit.ly/haxo-rpi3

PS: type on step 3, should be 16GB SD Card, not 16 MB

**Comment by Utopiah** [comment]
From https://github.com/cardonabits/haxo-hw/blob/main/docs/Quick%20Start%20Postcard.pdf

**Comment by jcard0na** [comment]
Thanks for letting me know!
I've fixed the online version the Quick Start Postcard.  Unfortunately, it is too late for the printed version... 😵‍💫

**Comment by jcard0na** [comment]
By the way, what is the point of this issue?  Just posting this links?  IOW, when should we close it?
The links are also [here](https://github.com/cardonabits/haxo-hw/blob/main/docs/instructions_safety.md), by the way.

**Comment by Utopiah** [comment]
I opened the issue before I found that document. IMHO it should be in https://github.com/cardonabits/haxo-hw#software to help newcomers.

**Comment by jcard0na** [comment]
Sounds good.  I'll go ahead and close the issue then.  The issue will still show up in search results.  Thanks!
