### ISSUE TITLE
No tunes below D

### ISSUE THREAD

**Issue by Domi1l** [cardonabits/haxo-hw#78]
Hello there,

First, I'd like to say that this project is very nice!

I'm new to the saxophone game and have never played an instrument before. I've been learning the saxophone for almost 4 months now, and my neighbors hate me :-P. So, I was searching for a solution to practice the saxophone after midnight, and I found it in the Haxophone. Thank you very much for this! 

I'm very satisfied with the Haxophone, but I'm not able to play the notes from Bb3 to D. Am I doing something wrong? Actually, I'm not able to connect a keyboard to my Raspberry Pi to see if all the keys work. Maybe there is another solution until I get my USB adapter?

I also tried to change the instrument sounds; that also doesn't work for me.

Maybe you have an idea how to fix this at the moment.

Thank you very much for this great Projekt

Cheers

**Comment by jcard0na** [comment]
Hi @Domi1l,

Thanks for the kind words, and I'm really sorry you can't get those notes to play.  Let's see if can solve this...
To narrow it down, are these the notes that do not sound?  Are you trying these same fingerings?

https://haxo-notemap.nn.r.appspot.com/?midinote=62  (D)
https://haxo-notemap.nn.r.appspot.com/?midinote=61  (C#)
https://haxo-notemap.nn.r.appspot.com/?midinote=60  (C)
https://haxo-notemap.nn.r.appspot.com/?midinote=59  (B)
https://haxo-notemap.nn.r.appspot.com/?midinote=58  (Bb)

How about low Eb?  Does it work?
https://haxo-notemap.nn.r.appspot.com/?midinote=63

If it does not, it could be that the keyswitch for L3 (col 1, row 7, https://github.com/cardonabits/haxo-hw/blob/main/docs/images/fingering-matrix.png) is not closing.
However, if D works but Eb does not, I don't think this could be a faulty keyswitch.

BTW, what Raspberry variant are you using?

Cheers,

**Comment by Domi1l** [comment]
Hey Javier, thanks for your fast respose :-)

so the Notes:

[https://haxo-notemap.nn.r.appspot.com/?midinote=62](url) (D) is playing
[https://haxo-notemap.nn.r.appspot.com/?midinote=63](url) (Eb) is playing

https://haxo-notemap.nn.r.appspot.com/?midinote=61 (C#) not playing
https://haxo-notemap.nn.r.appspot.com/?midinote=60 (C) not playing (only the tune D is playing)
https://haxo-notemap.nn.r.appspot.com/?midinote=59 (B) not playing
https://haxo-notemap.nn.r.appspot.com/?midinote=58 (Bb) not playing

Im using an Raspberry Pi Zero W V1.1. 
I also measured the single keys with an Multimeter to be sure that the circute is closing when im pressing the Button. That works well. Actually i dont know much songs with that kind of Low Notes, so im not in a Hurry :-D. Every other Note works just fine.

Thank you

**Comment by jcard0na** [comment]
Hi @Domi1l 

This really helps:

> https://haxo-notemap.nn.r.appspot.com/?midinote=62 (D) is playing
> (...)
> https://haxo-notemap.nn.r.appspot.com/?midinote=60 (C) not playing (only the tune D is playing)

The symptoms seems to point to key C (col 0, row 6 https://github.com/cardonabits/haxo-hw/blob/main/docs/images/fingering-matrix.png) not working.  Can you inspect this area of the haxophone?  Maybe look for damage, broken traces, missing D23 diode, poor/missing solder on the switch or any other reason for it not making contact.  Any of those failures would explain this behavior.

![Screenshot 2024-03-23 at 17 00 59](https://github.com/cardonabits/haxo-hw/assets/676181/e9239d8a-6674-49dd-bc3a-819a4fef4e74)

Let me know if you discover something 🤞 . 

Best,

**Comment by Domi1l** [comment]
WOW! 

Thank you very much Javier! The D23 Dioide is missing. Unfortunatly the circute Board i bought wasn't that good soldered. I have to resolder 2 diodes before i get even startet :-D. Im not an expert with electrical devices, can you give me a hint which kind of diod i have to buy to solve this Problem? I tried by myself but im not able to figure out. 

Thank you very much for your fast and good help.

**Comment by jcard0na** [comment]
Hi @Domi1l 

Nice to have it narrowed it down to a single diode.  Any surface mount diode with SOD-123 footprint will work. 
There are many, many alternatives:  https://octopart.com/search?q=diode+sod-123

BTW, where did you order the board from?  I'll make sure not to order from them... :yum:

**Comment by Domi1l** [comment]
I can't tell you where the PCB is from.  I ordered from Ebay. I think the seller ordered a bunch of PCB's to get a cheaper price and sell it to others who also want to build a Haxophone. Thank you again for your Help. Have a nice Day!

**Comment by Domi1l** [comment]
I soldered a new diode to D23. Now it works like a charm. Thank you again. That was so much Fun to build :-)
