### ISSUE TITLE
Make the tube longer

### ISSUE THREAD

**Issue by StaffanMelin** [cardonabits/haxo-hw#80]
I am afraid that spit from the tube will get on my Raspberry Pi 4. One simple solution is to angle the tube to one side.

Or make it longer?
![tube2](https://github.com/cardonabits/haxo-hw/assets/33361311/9dca1869-f35c-46df-a7ed-e29c112ae041)
![tube1](https://github.com/cardonabits/haxo-hw/assets/33361311/fbee8320-af8b-420b-ade6-12851974d6da)

**Comment by jcard0na** [comment]
I normally angle it to one side, actually the opposite side than you show on the picture so that it can be held in place by the right thumb rest.

**Comment by StaffanMelin** [comment]
Yeah, I saw that you mentioned this in the build instructions! :)
